fan:
  image-path: "/fan/images/"

server:
  port: 8888
  servlet:
    context-path: /fan

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.12.253.22:3306/fan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=5000&socketTimeout=10000
    username: root
    password: fan223
  data:
    redis:
      host: 1.12.253.22
      password: fan223

logging:
  level:
    root: info
  file:
    name: all.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7

# p6spy configuration
decorator:
  datasource:
    p6spy:
      log-format: "\n\tExecute Time: %(executionTime)ms\n\tExecute SQL: %(sql)"